version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: university_minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: university_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: ["9200:9200"]

  metabase:
    image: metabase/metabase:latest
    container_name: university_metabase
    ports: ["3000:3000"]
    depends_on:
      - elasticsearch

  # Note: Hive Metastore demande souvent une base SQL (Postgres/MySQL) 
  # Pour le jour 1, ces 3 services sont la priorité absolue.